var langstrings = new Array();


/** 
  English
*/

langstrings['en'] = new Array();
langstrings['en']['management'] = 'My cacaoweb';
langstrings['en']['searchplaceholder'] = 'Search...';
langstrings['en']['searchhints'] = '<small>Search for Movies, TV shows, Anime or paste a link</small>';
langstrings['en']['linknotrecognized'] = 'This type of link is not recognized by cacaoweb';
langstrings['en']['typeoflinks'] = '<small>Examples :<br>http://megavideo.com/?v=TUF78DFD <br>http://www.videobb.com/video/uGR5SO24apvI<br>http://127.0.0.1:4001/25614a53c9bcd3c537bb28a11174785f</small>';
langstrings['en']['outdated'] = 'Your version of cacaoweb is outdated, download the latest version <a href="http://www.cacaoweb.org/?noredirect=yes">here</a>';
langstrings['en']['nospaceleft'] = 'There is no space left on your media storage. cacaoweb will not work properly.';
langstrings['en']['noconnectivity'] = 'There is no internet connectivity for cacaoweb and it will not work';
langstrings['en']['permissionproblem'] = 'cacaoweb is currently blocked by the system (permission issue)';
langstrings['en']['next'] = 'Next >';
langstrings['en']['previous'] = '< Previous';
langstrings['en']['didyoumean'] = 'Did you mean: ';
langstrings['en']['noresults'] = 'No results were found';
langstrings['en']['showlink'] = 'link';
langstrings['en']['season'] = 'season';
langstrings['en']['episode'] = 'episode';
langstrings['en']['subtitles'] = 'subtitles';
langstrings['en']['cacaowebtitle'] = 'cacaoweb - watch your favorite TV shows and movies online freely';
langstrings['en']['cacaowebadmin'] = 'cacaoweb - Administration Interface';
langstrings['en']['mydownloads'] = 'My Downloads';
langstrings['en']['myuploads'] = 'My Uploads';
langstrings['en']['newupload'] = 'New Upload';
langstrings['en']['examples'] = 'examples :';
langstrings['en']['smalllink'] = '<small>Link : </small>';
langstrings['en']['smallembed'] = 'Embed : </small>';
langstrings['en']['smallupload'] = '<small>Upload a file</small>';
langstrings['en']['smallremoteupload'] = '<small>File URL:</small>';
langstrings['en']['browse'] = 'Browse';
langstrings['en']['remoteupload'] = 'Remote upload';
langstrings['en']['choose'] = 'Choose a file';
langstrings['en']['smalllargefile'] = '<small>Files larger than 2GB need to be uploaded with Chrome or Safari</small>';
langstrings['en']['uploadmeta'] = 'Video information (for the search engine)';
langstrings['en']['smallfilelink'] = '<small>cacaoweb link</small>';
langstrings['en']['movie'] = 'Movie';
langstrings['en']['tvshow'] = 'TV Show';
langstrings['en']['anime'] = 'Anime';
langstrings['en']['documentary'] = 'Documentary';
langstrings['en']['music'] = 'Music';
langstrings['en']['file'] = 'File';
langstrings['en']['smallcontenttype'] = '<small>Type</small>';
langstrings['en']['smalllanguage'] = '<small>Language</small>';
langstrings['en']['smallsubtitles'] = '<small>Subtitles</small>';
langstrings['en']['smalltitle'] = '<small>Title</small>';
langstrings['en']['smallshowtitle'] = '<small>Show title</small>';
langstrings['en']['smallseason'] = '<small>Season</small>';
langstrings['en']['smallepisode'] = '<small>Episode</small>';
langstrings['en']['addashow'] = 'TV show not in the list? Add it <a href="http://forum.cacaoweb.org/index.php?topic=678.0"><u>here</u></a>';
langstrings['en']['submit'] = 'Upload';
langstrings['en']['h2cacaowebstatus'] = 'cacaoweb status';
langstrings['en']['cacaowebactions'] = 'cacaoweb actions';
langstrings['en']['turnoff'] = 'turn off';
langstrings['en']['uninstall'] = 'uninstall';
langstrings['en']['backmainpage'] = 'back to main page';
langstrings['en']['natnotcone'] = "Your router is currently not supported by cacaoweb (it's not a cone)";
langstrings['en']['notconnected'] = "cacaoweb is not connected to the network yet";
langstrings['en']['natnotp2pfriendly'] = "Your router is not compatible with cacaoweb, you will experience very slow speed, see <a href='http://forum.cacaoweb.org/index.php?topic=33.0' target=\"_newtab\">here</a>";
langstrings['en']['workingfine'] = "cacaoweb is working fine";
langstrings['en']['turnedoff'] = "cacaoweb has been turned off";
langstrings['en']['uninstalled'] = "cacaoweb has been successfully uninstalled";
langstrings['en']['notloggedin'] = "Your are not logged in";
langstrings['en']['welcome'] = "Welcome ";
langstrings['en']['mymoney'] = "You have {1} credits in your account. <a href='javascript:showcreditsform();'><u>Click here to add credits</u>.</a>";
langstrings['en']['buywithpaypal'] = "Buy with Paypal";
langstrings['en']['numberofcreditstobuy'] = "Number of credits to buy:";
langstrings['en']['name'] = "Name";
langstrings['en']['password'] = "Password";
langstrings['en']['login'] = "Login";
langstrings['en']['create'] = "Create my account";
langstrings['en']['register'] = "register";
langstrings['en']['paidcontentsmall'] = "<small>Paid content</small>";
langstrings['en']['previewsmall'] = "<small>Preview allowed</small>";
langstrings['en']['numberofcreditssmall'] = "<small>Credits required</small>";
langstrings['en']['share'] = "Share";
langstrings['en']['more'] = "More";
langstrings['en']['help'] = "Help";
langstrings['en']['forum'] = "Forum";
langstrings['en']['download'] = "Download";
langstrings['en']['developers'] = "Developers";
langstrings['en']['makemoney'] = "Make money";
langstrings['en']['en'] = "english";
langstrings['en']['fr'] = "french";
langstrings['en']['it'] = "italian";
langstrings['en']['es'] = "spanish";
langstrings['en']['pt'] = "portuguese";
langstrings['en']['de'] = "german";
langstrings['en']['hu'] = "hungarish";
langstrings['en']['pl'] = "polish";
langstrings['en']['ru'] = "russian";
langstrings['en']['ar'] = "arabic";
langstrings['en']['cn'] = "chinese";
langstrings['en']['hi'] = "hindi";
langstrings['en']['jp'] = "japanese";
langstrings['en']['vn'] = "vietnamese";



/** 
  French
*/

langstrings['fr'] = new Array();
langstrings['fr']['management'] = 'Mon cacaoweb';
langstrings['fr']['searchplaceholder'] = 'Recherchez...';
langstrings['fr']['searchhints'] = '<small>Recherchez des séries, films, mangas ou collez un lien</small>';
langstrings['fr']['linknotrecognized'] = 'Ce type de lien n\'est pas reconnu par cacaoweb';
langstrings['fr']['typeoflinks'] = '<small>Exemples de liens reconnus:<br>http://megavideo.com/?v=TUF78DFD <br>http://www.videobb.com/video/uGR5SO24apvI<br>http://127.0.0.1:4001/25614a53c9bcd3c537bb28a11174785f</small>';
langstrings['fr']['outdated'] = 'Votre version de cacaoweb n\'est pas à jour, téléchargez la dernière version <a href="http://www.cacaoweb.org/?noredirect=yes">ici</a>';
langstrings['fr']['nospaceleft'] = 'Il n\'y a plus de place sur votre système de stockage, cacaoweb ne va plus fonctionner correctement.';
langstrings['fr']['noconnectivity'] = 'cacaoweb n\'a pas de connectivité internet et donc ne fonctionne pas';
langstrings['fr']['permissionproblem'] = 'cacaoweb est actuellement bloqué par le système (problème de permissions)';
langstrings['fr']['next'] = 'Suivant >';
langstrings['fr']['previous'] = '< Précédent';
langstrings['fr']['didyoumean'] = 'Vous voulez dire: ';
langstrings['fr']['noresults'] = 'La recherche n\'a retourné aucun résultat';
langstrings['fr']['showlink'] = 'lien';
langstrings['fr']['season'] = 'saison';
langstrings['fr']['episode'] = 'épisode';
langstrings['fr']['subtitles'] = 'sous-titres';
langstrings['fr']['cacaowebtitle'] = 'cacaoweb - regardez vos séries et films favoris en ligne librement';
langstrings['fr']['cacaowebadmin'] = 'cacaoweb - Interface d\'administration';
langstrings['fr']['mydownloads'] = 'Mes Téléchargements';
langstrings['fr']['myuploads'] = 'Mes Téléversements';
langstrings['fr']['newupload'] = 'Nouveau Téléversement';
langstrings['fr']['examples'] = 'exemples :';
langstrings['fr']['smalllink'] = '<small>Lien : </small>';
langstrings['fr']['smallembed'] = '<small>Embed : </small>';
langstrings['fr']['smallupload'] = '<small>Téléverser un fichier</small>';
langstrings['fr']['smallremoteupload'] = '<small>URL du fichier:</small>';
langstrings['fr']['browse'] = 'Parcourir';
langstrings['fr']['remoteupload'] = 'Téléversement distant';
langstrings['fr']['choose'] = 'Choisir un fichier';
langstrings['fr']['smalllargefile'] = '<small>Files larger than 2GB need to be uploaded with Chrome or Safari</small>';
langstrings['fr']['uploadmeta'] = 'Informations sur la vidéo (pour le moteur de recherche)';
langstrings['fr']['smallfilelink'] = '<small>lien cacaoweb</small>';
langstrings['fr']['movie'] = 'Film';
langstrings['fr']['tvshow'] = 'Série';
langstrings['fr']['anime'] = 'Manga';
langstrings['fr']['documentary'] = 'Documentaire';
langstrings['fr']['music'] = 'Musique';
langstrings['fr']['file'] = 'Fichier';
langstrings['fr']['smallcontenttype'] = '<small>Type</small>';
langstrings['fr']['smalllanguage'] = '<small>Langage</small>';
langstrings['fr']['smallsubtitles'] = '<small>Sous-titres</small>';
langstrings['fr']['smalltitle'] = '<small>Titre</small>';
langstrings['fr']['smallshowtitle'] = '<small>Titre de la série</small>';
langstrings['fr']['smallseason'] = '<small>Saison</small>';
langstrings['fr']['smallepisode'] = '<small>Episode</small>';
langstrings['fr']['addashow'] = 'La série n\'est pas dans la liste? Ajoutez-la <a href="http://forum.cacaoweb.org/index.php?topic=679.0"><u>ici</u></a>';
langstrings['fr']['submit'] = 'Envoyer';
langstrings['fr']['h2cacaowebstatus'] = 'statut de cacaoweb';
langstrings['fr']['cacaowebactions'] = 'actions cacaoweb';
langstrings['fr']['turnoff'] = 'éteindre';
langstrings['fr']['uninstall'] = 'désinstaller';
langstrings['fr']['backmainpage'] = 'retour à la page principale';
langstrings['fr']['natnotcone'] = "Votre routeur n'est pas compatible avec cacaoweb (ce n'est pas un cône)";
langstrings['fr']['notconnected'] = "cacaoweb n'est pas encore connecté au réseau";
langstrings['fr']['natnotp2pfriendly'] = "Votre routeur n'est pas compatible avec cacaoweb, la vitesse de téléchargement va être très faible, voir <a href='http://forum.cacaoweb.org/index.php?topic=33.0' target=\"_newtab\">ici</a>";
langstrings['fr']['workingfine'] = "Tout marche parfaitement";
langstrings['fr']['turnedoff'] = "cacaoweb est maintenant éteint";
langstrings['fr']['uninstalled'] = "cacaoweb est maintenant désinstallé";
langstrings['fr']['notloggedin'] = "Vous ne vous êtes pas identifié";
langstrings['fr']['welcome'] = "Bienvenu ";
langstrings['fr']['mymoney'] = "Vous avez {1} crédits. <a href='javascript:showcreditsform();'><u>Cliquez ici pour ajouter des crédits</u>.</a>";
langstrings['fr']['buywithpaypal'] = "Acheter avec Paypal";
langstrings['fr']['numberofcreditstobuy'] = "Nombre de crédits à acheter:";
langstrings['fr']['name'] = "Nom";
langstrings['fr']['password'] = "Mot de passe";
langstrings['fr']['login'] = "S'identifier";
langstrings['fr']['create'] = "Créer mon compte";
langstrings['fr']['register'] = "s'enregistrer";
langstrings['fr']['paidcontentsmall'] = "<small>Contenu payant</small>";
langstrings['fr']['previewsmall'] = "<small>Aperçu autorisé</small>";
langstrings['fr']['numberofcreditssmall'] = "<small>Crédits requis</small>";
langstrings['fr']['share'] = "Partager";
langstrings['fr']['more'] = "Plus";
langstrings['fr']['help'] = "Aide";
langstrings['fr']['forum'] = "Forum";
langstrings['fr']['download'] = "Télécharger";
langstrings['fr']['developers'] = "Développeurs";
langstrings['fr']['makemoney'] = "Gagner de l'argent";
langstrings['fr']['en'] = "anglais";
langstrings['fr']['fr'] = "français";
langstrings['fr']['it'] = "italien";
langstrings['fr']['es'] = "espagnol";
langstrings['fr']['pt'] = "portugais";
langstrings['fr']['de'] = "allemand";
langstrings['fr']['hu'] = "hongrois";
langstrings['fr']['pl'] = "polonais";
langstrings['fr']['ru'] = "russe";
langstrings['fr']['ar'] = "arabe";
langstrings['fr']['cn'] = "chinois";
langstrings['fr']['hi'] = "hindi";
langstrings['fr']['jp'] = "japonais";
langstrings['fr']['vn'] = "vietnamien";


/** 
  Italian
*/

langstrings['it'] = new Array();
langstrings['it']['management'] = 'Mio Cacaoweb';
langstrings['it']['searchplaceholder'] = 'Search...';
langstrings['it']['searchhints'] = '<small>Ricerca Film, Serie TV o incolla un link</small>';
langstrings['it']['linknotrecognized'] = 'Questo tipo di link non è ancora supportato da cacaoweb';
langstrings['it']['typeoflinks'] = '<small>Esempio :<br>http://megavideo.com/?v=TUF78DFD <br>http://www.videobb.com/video/uGR5SO24apvI<br>http://127.0.0.1:4001/25614a53c9bcd3c537bb28a11174785f</small>';
langstrings['it']['outdated'] = 'La tua versione di cacaoweb è obsoleta, scarica l\'ultima versione <a href="http://www.cacaoweb.org/?noredirect=yes">qui</a>';
langstrings['it']['nospaceleft'] = 'Non c\'è spazio sul tuo supporto di archiviazione. Cacaoweb non funziona correttamente.';
langstrings['it']['noconnectivity'] = 'Per funzionare cacaoweb necessità di una connessione a internet.';
langstrings['it']['permissionproblem'] = 'Cacaoweb è bloccato dal tuo sistema operativo o antivirus (problema di autorizzazione)';
langstrings['it']['next'] = 'Avanti >';
langstrings['it']['previous'] = '< Indietro';
langstrings['it']['didyoumean'] = 'Voce disambigua, cosa intendi: ';
langstrings['it']['noresults'] = 'Nessun risultato trovato';
langstrings['it']['showlink'] = 'Link';
langstrings['it']['season'] = 'Stagione';
langstrings['it']['episode'] = 'Episodio';
langstrings['it']['subtitles'] = 'sottotitoli';
langstrings['it']['cacaowebtitle'] = 'Cacaoweb - Guarda Film o Serie TV Online in Streaming';
langstrings['it']['cacaowebadmin'] = 'Cacaoweb - Interfaccia di Amministrazione';
langstrings['it']['mydownloads'] = 'Miei Download';
langstrings['it']['myuploads'] = 'Miei Uploads';
langstrings['it']['newupload'] = 'Nuovo Upload';
langstrings['it']['examples'] = 'esempio :';
langstrings['it']['smalllink'] = '<small>Link : </small>';
langstrings['it']['smallembed'] = '<small>Embed : </small>';
langstrings['it']['smallupload'] = '<small>Carica un file</small>';
langstrings['it']['smallremoteupload'] = '<small>URL del file:</small>';
langstrings['it']['browse'] = 'Browse';
langstrings['it']['remoteupload'] = 'Upload Remoto';
langstrings['it']['choose'] = 'Scegli file';
langstrings['it']['smalllargefile'] = '<small>Per caricare file più grandi di 2 GB devi utilizzare Chrome o Safari</small>';
langstrings['it']['uploadmeta'] = 'Informazioni video (per il motore di ricerca)';
langstrings['it']['smallfilelink'] = '<small>link cacaoweb</small>';
langstrings['it']['movie'] = 'Movie';
langstrings['it']['tvshow'] = 'Serie TV';
langstrings['it']['anime'] = 'Anime';
langstrings['it']['documentary'] = 'Documentario';
langstrings['it']['music'] = 'Musica';
langstrings['it']['file'] = 'File';
langstrings['it']['smallcontenttype'] = '<small>Genere</small>';
langstrings['it']['smalllanguage'] = '<small>Lingua</small>';
langstrings['it']['smallsubtitles'] = '<small>Sottotitoli</small>';
langstrings['it']['smalltitle'] = '<small>Titolo</small>';
langstrings['it']['smallshowtitle'] = '<small>Mostra titolo</small>';
langstrings['it']['smallseason'] = '<small>Stagione</small>';
langstrings['it']['smallepisode'] = '<small>Episodio</small>';
langstrings['it']['submit'] = 'Upload';
langstrings['it']['h2cacaowebstatus'] = 'Stato cacaoweb';
langstrings['it']['cacaowebactions'] = 'Azione cacaoweb';
langstrings['it']['turnoff'] = 'Esci';
langstrings['it']['uninstall'] = 'Disinstalla';
langstrings['it']['backmainpage'] = 'Torna alla pagina principale';
langstrings['it']['natnotcone'] = "Il tuo router non è attualmente supportato da cacaoweb (<a href='http://forum.cacaoweb.org/index.php?topic=33.0'>forum</a>)";
langstrings['it']['notconnected'] = "cacaoweb non è ancora connesso alla rete";
langstrings['it']['natnotp2pfriendly'] = "Il tuo router non è attualemnete supportato da cacaoweb (<a href='http://forum.cacaoweb.org/index.php?topic=33.0' target=\"_newtab\">forum</a>)";
langstrings['it']['workingfine'] = "Cacaoweb sta funzionando correttamente";
langstrings['it']['turnedoff'] = "Sei uscito da Cacaoweb correttamente";
langstrings['it']['uninstalled'] = "cacaoweb è stato disinstallato con successo";
langstrings['it']['notloggedin'] = "Non sei loggato";
langstrings['it']['welcome'] = "Benvenuto ";
langstrings['it']['mymoney'] = "Hai {1} crediti nel tuo account. <a href='javascript:showcreditsform();'><u>Clicca quì per acquistare crediti.</u></a>";
langstrings['it']['buywithpaypal'] = "Acquista con Paypal";
langstrings['it']['numberofcreditstobuy'] = "Numero di crediti da acquistare:";
langstrings['it']['name'] = "Nome";
langstrings['it']['password'] = "Password";
langstrings['it']['login'] = "Login";
langstrings['it']['create'] = "Crea account";
langstrings['it']['register'] = "register";
langstrings['it']['paidcontentsmall'] = "<small>Contenuto a pagamento</small>";
langstrings['it']['previewsmall'] = "<small>Permesso di anteprima</small>";
langstrings['it']['numberofcreditssmall'] = "<small>Crediti richiesti</small>";
langstrings['it']['share'] = "Share";
langstrings['it']['more'] = "More";
langstrings['it']['help'] = "Help";
langstrings['it']['forum'] = "Forum";
langstrings['it']['download'] = "Download";
langstrings['it']['developers'] = "Developers";
langstrings['it']['makemoney'] = "Make money";
langstrings['it']['en'] = "english";
langstrings['it']['fr'] = "french";
langstrings['it']['it'] = "italian";
langstrings['it']['es'] = "spanish";
langstrings['it']['pt'] = "portuguese";
langstrings['it']['de'] = "german";
langstrings['it']['hu'] = "hungarish";
langstrings['it']['pl'] = "polish";
langstrings['it']['ru'] = "russian";
langstrings['it']['ar'] = "arabic";
langstrings['it']['cn'] = "chinese";
langstrings['it']['hi'] = "hindi";
langstrings['it']['jp'] = "japanese";
langstrings['it']['vn'] = "vietnamese";


/** 
  Polish
  Grzegorz Witczak   kavillock.at.gmail.dot.com
*/

langstrings['pl'] = new Array();
langstrings['pl']['management'] = 'Mój cacaoweb';
langstrings['pl']['searchplaceholder'] = 'Wyszukaj...';
langstrings['pl']['searchhints'] = '<small>Wyszukaj filmy, programy telewizyjne, albo wklej link</small>';
langstrings['pl']['linknotrecognized'] = 'Typ linku nie jest obsługiwany przez cacaoweb';
langstrings['pl']['typeoflinks'] = '<small>Przykłady :<br>http://megavideo.com/?v=TUF78DFD <br>http://www.videobb.com/video/uGR5SO24apvI<br>http://127.0.0.1:4001/25614a53c9bcd3c537bb28a11174785f</small>';
langstrings['pl']['outdated'] = 'Nowa wersja cacaoweb wydana, pobierz najnowszą wersję <a href="http://www.cacaoweb.org/?noredirect=yes">tutaj</a>';
langstrings['pl']['nospaceleft'] = 'Brak miejsca na dysku. Cacaoweb może działać niepoprawnie.';
langstrings['pl']['noconnectivity'] = 'Nie ma połączenia z internetem dla cacaoweb, program nie będzie działać';
langstrings['pl']['permissionproblem'] = 'Cacaoweb jest aktualnie zablokowany przez system (brak zezwolenia)';
langstrings['pl']['next'] = 'Następna >';
langstrings['pl']['previous'] = '< Poprzednia';
langstrings['pl']['didyoumean'] = 'Czy chodziło ci o: ';
langstrings['pl']['noresults'] = 'Brak wyników';
langstrings['pl']['showlink'] = 'link';
langstrings['pl']['season'] = 'sezon';
langstrings['pl']['episode'] = 'odcinek';
langstrings['pl']['subtitles'] = 'Napisy';
langstrings['pl']['cacaowebtitle'] = 'cacaoweb - Oglądaj swobodnie swoje ulubione programy telewizyjne i filmy online';
langstrings['pl']['cacaowebadmin'] = 'cacaoweb - Administracja Interfejsem';
langstrings['pl']['mydownloads'] = 'Pobieranie';
langstrings['pl']['myuploads'] = 'Wysyłanie';
langstrings['pl']['newupload'] = 'Wyślij więcej';
langstrings['pl']['examples'] = 'przykłady :';
langstrings['pl']['smalllink'] = '<small>Link : </small>';
langstrings['pl']['smallembed'] = '<small>Wstaw : </small>';
langstrings['pl']['smallupload'] = '<small>Wyślij plik</small>';
langstrings['pl']['smallremoteupload'] = '<small>Adres URL:</small>';
langstrings['pl']['browse'] = 'Przeglądaj';
langstrings['pl']['remoteupload'] = 'Remote upload';
langstrings['pl']['choose'] = 'Wybierz Plik';
langstrings['pl']['smalllargefile'] = '<small>Pliki większe niż 2GB muszą byś wysyłane za pomocą Chrome lub Safari</small>';
langstrings['pl']['uploadmeta'] = 'Informacje o pliku';
langstrings['pl']['smallfilelink'] = '<small>Link cacaoweb</small>';
langstrings['pl']['movie'] = 'Film';
langstrings['pl']['tvshow'] = 'Program TV';
langstrings['pl']['anime'] = 'Anime';
langstrings['pl']['documentary'] = 'Dokumentalny';
langstrings['pl']['music'] = 'Muzyka';
langstrings['pl']['file'] = 'Plik';
langstrings['pl']['smallcontenttype'] = '<small>Typ</small>';
langstrings['pl']['smalllanguage'] = '<small>Język</small>';
langstrings['pl']['smallsubtitles'] = '<small>Napisy</small>';
langstrings['pl']['smalltitle'] = '<small>Tytuł</small>';
langstrings['pl']['smallshowtitle'] = '<small>Pokaż tytuł</small>';
langstrings['pl']['smallseason'] = '<small>Sezon</small>';
langstrings['pl']['smallepisode'] = '<small>Odcinek</small>';
langstrings['pl']['submit'] = 'Wyślij';
langstrings['pl']['h2cacaowebstatus'] = 'Status cacaoweb';
langstrings['pl']['cacaowebactions'] = 'Akcje cacaoweb';
langstrings['pl']['turnoff'] = 'Wyłącz';
langstrings['pl']['uninstall'] = 'Odinstaluj';
langstrings['pl']['backmainpage'] = 'Wróć do strony głównej';
langstrings['pl']['natnotcone'] = "Twój router nie jest obecnie obsługiwany przez cacaoweb (nie jest to stożek)";
langstrings['pl']['notconnected'] = "Cacaoweb nie jest podłączony do sieci";
langstrings['pl']['natnotp2pfriendly'] = "Twój router nie jest obecnie obsługiwany przez cacaoweb, zobacz (<a href='http://forum.cacaoweb.org/index.php?topic=33.0' target=\"_newtab\">forum</a>)";
langstrings['pl']['workingfine'] = "Cacaoweb działa poprawnie";
langstrings['pl']['turnedoff'] = "Cacaoweb został wyłączony";
langstrings['pl']['uninstalled'] = "Cacaoweb został poprawnie odinstalowany";
langstrings['pl']['notloggedin'] = "Nie jesteś zalogowany";
langstrings['pl']['welcome'] = "Witaj ";
langstrings['pl']['mymoney'] = "Posiadasz {1} kredytów na koncie. <a href='javascript:showcreditsform();'><u>Kliknij tutaj aby zakupić kredyty</u>.</a>";
langstrings['pl']['buywithpaypal'] = "Kup z Paypal";
langstrings['pl']['numberofcreditstobuy'] = "Liczba kredytów do zakupienia:";
langstrings['pl']['name'] = "Imię";
langstrings['pl']['password'] = "Hasło";
langstrings['pl']['login'] = "Zaloguj się";
langstrings['pl']['create'] = "Utwórz konto";
langstrings['pl']['register'] = "Zarejestruj się";
langstrings['pl']['paidcontentsmall'] = "<small>Płatna zawartość</small>";
langstrings['pl']['previewsmall'] = "<small>Podgląd dostępny</small>";
langstrings['pl']['numberofcreditssmall'] = "<small>Wymaga kredytów:</small>";
langstrings['pl']['share'] = "Poleć";
langstrings['pl']['more'] = "Więcej";
langstrings['pl']['help'] = "Pomoc";
langstrings['pl']['forum'] = "Forum";
langstrings['pl']['download'] = "Pobierz";
langstrings['pl']['developers'] = "Deweloperzy";
langstrings['pl']['makemoney'] = "Zarób pieniądze";
langstrings['pl']['en'] = "angielski";
langstrings['pl']['fr'] = "francuski";
langstrings['pl']['it'] = "włoski";
langstrings['pl']['es'] = "hiszpański";
langstrings['pl']['pt'] = "portugalski";
langstrings['pl']['de'] = "niemiecki";
langstrings['pl']['hu'] = "węgierski";
langstrings['pl']['pl'] = "polski";
langstrings['pl']['ru'] = "rosyjski";
langstrings['pl']['ar'] = "arabski";
langstrings['pl']['cn'] = "chiński";
langstrings['pl']['hi'] = "hindi";
langstrings['pl']['jp'] = "japoński";
langstrings['pl']['vn'] = "wietnamski";



/** 
Spanish
*/

langstrings['es'] = new Array();
langstrings['es']['management'] = 'Mi cacaoweb';
langstrings['es']['searchplaceholder'] = 'Buscar...';
langstrings['es']['searchhints'] = '<small>Busca Películas, Programas de TV, Anime o pega un enlace</small>';
langstrings['es']['linknotrecognized'] = 'cacaoweb no reconoce este tipo de enlaces';
langstrings['es']['typeoflinks'] = '<small>Ejemplos:<br>http://megavideo.com/?v=TUF78DFD <br>http://www.videobb.com/video/uGR5SO24apvI<br>http://127.0.0.1:4001/25614a53c9bcd3c537bb28a11174785f</small>';
langstrings['es']['outdated'] = 'Hay una nueva versión de cacaoweb. Descárgala <a href="http://www.cacaoweb.org/?noredirect=yes">aquí</a>';
langstrings['es']['nospaceleft'] = 'No queda espacio en tu disco duro. cacaoweb podría no funcionar bien.';
langstrings['es']['noconnectivity'] = 'No existe ninguna conexión a internet para cacaoweb, y no funcionará';
langstrings['es']['permissionproblem'] = 'cacaoweb está siendo bloqueado por el sistema (error de permisos)';
langstrings['es']['next'] = 'Siguiente >';
langstrings['es']['previous'] = '< Anterior';
langstrings['es']['didyoumean'] = '¿Quisiste decir... ';
langstrings['es']['noresults'] = 'No se encontró ningún resultado';
langstrings['es']['showlink'] = 'enlace';
langstrings['es']['season'] = 'temporada';
langstrings['es']['episode'] = 'episodio';
langstrings['es']['subtitles'] = 'subtítulos';
langstrings['es']['cacaowebtitle'] = 'cacaoweb - mira tus programas de TV y películas en línea gratis';
langstrings['es']['cacaowebadmin'] = 'cacaoweb - Interfaz de Administración';
langstrings['es']['mydownloads'] = 'Mis Descargas';
langstrings['es']['myuploads'] = 'Mis Subidas';
langstrings['es']['newupload'] = 'Nueva Subida';
langstrings['es']['examples'] = 'ejemplos:';
langstrings['es']['smalllink'] = '<small>Enlace: </small>';
langstrings['es']['smallembed'] = 'Incrustar: </small>';
langstrings['es']['smallupload'] = '<small>Subir un archvio</small>';
langstrings['es']['smallremoteupload'] = '<small>URL del Archivo:</small>';
langstrings['es']['browse'] = 'Explorar';
langstrings['es']['remoteupload'] = 'Subida remota';
langstrings['es']['choose'] = 'Elige un archivo';
langstrings['es']['smalllargefile'] = '<small>Se necesita Chrome o Safari para subir archivos más grandes de 2GB</small>';
langstrings['es']['uploadmeta'] = 'Información del vídeo (para el motor de búsqueda)';
langstrings['es']['smallfilelink'] = '<small>enlace cacaoweb</small>';
langstrings['es']['movie'] = 'Película';
langstrings['es']['tvshow'] = 'Programa de TV';
langstrings['es']['anime'] = 'Anime';
langstrings['es']['documentary'] = 'Documental';
langstrings['es']['music'] = 'Música';
langstrings['es']['file'] = 'Archivo';
langstrings['es']['smallcontenttype'] = '<small>Tipo</small>';
langstrings['es']['smalllanguage'] = '<small>Idioma</small>';
langstrings['es']['smallsubtitles'] = '<small>Subtítulos</small>';
langstrings['es']['smalltitle'] = '<small>Título</small>';
langstrings['es']['smallshowtitle'] = '<small>Mostrar título</small>';
langstrings['es']['smallseason'] = '<small>Temporada</small>';
langstrings['es']['smallepisode'] = '<small>Episodio</small>';
langstrings['es']['addashow'] = '¿Tu programa no está en la lista? Añádelo <a href="http://forum.cacaoweb.org/index.php?topic=678.0"><u>aquí</u></a>';
langstrings['es']['submit'] = 'Subir';
langstrings['es']['h2cacaowebstatus'] = 'estado de cacaoweb';
langstrings['es']['cacaowebactions'] = 'acciones de cacaoweb';
langstrings['es']['turnoff'] = 'apagar';
langstrings['es']['uninstall'] = 'desinstalar';
langstrings['es']['backmainpage'] = 'volver a la página principal';
langstrings['es']['natnotcone'] = "cacaoweb no soporta tu router";
langstrings['es']['notconnected'] = "cacaoweb aún no está conectado a internet";
langstrings['es']['natnotp2pfriendly'] = "Tu router no es compatible con cacaoweb, notarás mucha lentitud, visita <a href='http://forum.cacaoweb.org/index.php?topic=33.0'>el foro</a>";
langstrings['es']['workingfine'] = "cacaoweb funciona bien";
langstrings['es']['turnedoff'] = "cacaoweb ha sido apagado";
langstrings['es']['uninstalled'] = "cacaoweb ha sido desinstalado";
langstrings['es']['notloggedin'] = "No has iniciado sesión";
langstrings['es']['welcome'] = "Bienvenido ";
langstrings['es']['mymoney'] = "Tienes {1} créditos en tu cuenta. <a href='javascript:showcreditsform();'>¡Añade créditos!</a>";
langstrings['es']['buywithpaypal'] = "Comprar con PayPal";
langstrings['es']['numberofcreditstobuy'] = "Nº de créditos a comprar:";
langstrings['es']['name'] = "Nombre";
langstrings['es']['password'] = "Contraseña";
langstrings['es']['login'] = "Iniciar sesión";
langstrings['es']['create'] = "Crear mi cuenta";
langstrings['es']['register'] = "registrarse";
langstrings['es']['paidcontentsmall'] = "<small>Contenido de pago</small>";
langstrings['es']['previewsmall'] = "<small>Adelanto disponible</small>";
langstrings['es']['numberofcreditssmall'] = "<small>Necesitas más créditos</small>";
langstrings['es']['share'] = "Compartir";
langstrings['es']['more'] = "Más";
langstrings['es']['help'] = "Ayuda";
langstrings['es']['forum'] = "Foro";
langstrings['es']['download'] = "Descargar";
langstrings['es']['developers'] = "Desarrolladores";
langstrings['es']['makemoney'] = "Haz dinero";
langstrings['es']['es'] = "inglés";
langstrings['es']['fr'] = "francés";
langstrings['es']['it'] = "italiano";
langstrings['es']['es'] = "español";
langstrings['es']['pt'] = "portugués";
langstrings['es']['de'] = "alemán";
langstrings['es']['hu'] = "húngaro";
langstrings['es']['pl'] = "polaco";
langstrings['es']['ru'] = "ruso";
langstrings['es']['ar'] = "árabe";
langstrings['es']['cn'] = "chino";
langstrings['es']['hi'] = "hindi";
langstrings['es']['jp'] = "japonés";
langstrings['es']['vn'] = "vietnamita";
